-- mysql
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS ISSUE;
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE ISSUE (
    ISSUE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID VARCHAR(50) NOT NULL,
    TITLE VARCHAR(120) NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE COMMENT (
    COMMENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID VARCHAR(50) NOT NULL,
    ISSUE_ID BIGINT NOT NULL,
    CONTENT VARCHAR(2000) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE COMMENT ADD FOREIGN KEY (ISSUE_ID) REFERENCES ISSUE (ISSUE_ID);
ALTER TABLE ISSUE ADD FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);
ALTER TABLE COMMENT ADD FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID);
