name: Deploy to WAS Server via Bastion host

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Deploy # environment secret 사용을 위한 설정
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Override application.yml with environment secrets
      run: echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yml

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build/libs/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: Deploy # environment secret 사용을 위한 설정

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create SSH key, SSH directory
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/private-key.pem
          chmod 600 ~/private-key.pem
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.BASTION_HOST_IP }} >> ~/.ssh/known_hosts
          
    - name: Transfer file to Bastion Host
      run: |
        scp -i ~/private-key.pem issue-tracker-0.0.1-SNAPSHOT.jar ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST_IP }}:/home/${{ secrets.BASTION_USER }}
        scp -i ~/private-key.pem ~/private-key.pem ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST_IP }}:/home/${{ secrets.BASTION_USER }}
        
    - name: Transfer file to WAS Server
      run: |
        ssh -i ~/private-key.pem ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST_IP }} \
        "chmod 600 ~/private-key.pem && \
        scp -i ~/private-key.pem /home/${{ secrets.BASTION_USER }}/issue-tracker-0.0.1-SNAPSHOT.jar ${{ secrets.WAS_USER }}@${{ secrets.WAS_HOST_IP }}:/home/${{ secrets.WAS_USER }}"
        
    - name: Start application on WAS Server
      run: |
        ssh -i ~/private-key.pem ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST_IP }} \
        "ssh -i ~/private-key.pem ${{ secrets.WAS_USER }}@${{ secrets.WAS_HOST_IP }} 'chmod +x ./run.sh && ./run.sh'"
    
