name: Deploy to Amazon S3

on:
  push:
    branches:
      - dev-fe

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: Set environment variables
        run: |
          echo "VITE_APP_S3_BUCKET_NAME=${{ secrets.VITE_APP_S3_BUCKET_NAME }}" >> $GITHUB_ENV
          echo "VITE_APP_S3_REGION=${{ secrets.VITE_APP_S3_REGION }}" >> $GITHUB_ENV
          echo "VITE_APP_S3_ACCESS_KEY_ID=${{ secrets.VITE_APP_S3_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "VITE_APP_S3_SECRET_ACCESS_KEY=${{ secrets.VITE_APP_S3_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Build
        run: |
          cd front
          npm run build
          echo "Build completed. Listing contents of the build directory:"
          ls -al ./build/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync ./front/build/ s3://fe-issue-tracker-s3/ --acl public-read --delete

      - name: Notify Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"배포가 성공적으로 완료되었습니다!"}' ${{ secrets.SLACK_WEBHOOK_URL }}
